/* Auto-generated by genmsg_cpp for file /home/mckoval/ros-diamondback/navi_stack/stereo_plane/msg/Plane.msg */
#ifndef STEREO_PLANE_MESSAGE_PLANE_H
#define STEREO_PLANE_MESSAGE_PLANE_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Point.h"
#include "geometry_msgs/Vector3.h"

namespace stereo_plane
{
template <class ContainerAllocator>
struct Plane_ : public ros::Message
{
  typedef Plane_<ContainerAllocator> Type;

  Plane_()
  : header()
  , point()
  , normal()
  {
  }

  Plane_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , point(_alloc)
  , normal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
   ::geometry_msgs::Point_<ContainerAllocator>  point;

  typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _normal_type;
   ::geometry_msgs::Vector3_<ContainerAllocator>  normal;


private:
  static const char* __s_getDataType_() { return "stereo_plane/Plane"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "e6dad39e8527110ab026c6017616f37b"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "Header header\n\
geometry_msgs/Point   point\n\
geometry_msgs/Vector3 normal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, header);
    ros::serialization::serialize(stream, point);
    ros::serialization::serialize(stream, normal);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, header);
    ros::serialization::deserialize(stream, point);
    ros::serialization::deserialize(stream, normal);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(header);
    size += ros::serialization::serializationLength(point);
    size += ros::serialization::serializationLength(normal);
    return size;
  }

  typedef boost::shared_ptr< ::stereo_plane::Plane_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stereo_plane::Plane_<ContainerAllocator>  const> ConstPtr;
}; // struct Plane
typedef  ::stereo_plane::Plane_<std::allocator<void> > Plane;

typedef boost::shared_ptr< ::stereo_plane::Plane> PlanePtr;
typedef boost::shared_ptr< ::stereo_plane::Plane const> PlaneConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::stereo_plane::Plane_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::stereo_plane::Plane_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace stereo_plane

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::stereo_plane::Plane_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e6dad39e8527110ab026c6017616f37b";
  }

  static const char* value(const  ::stereo_plane::Plane_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe6dad39e8527110aULL;
  static const uint64_t static_value2 = 0xb026c6017616f37bULL;
};

template<class ContainerAllocator>
struct DataType< ::stereo_plane::Plane_<ContainerAllocator> > {
  static const char* value() 
  {
    return "stereo_plane/Plane";
  }

  static const char* value(const  ::stereo_plane::Plane_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::stereo_plane::Plane_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
geometry_msgs/Point   point\n\
geometry_msgs/Vector3 normal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const  ::stereo_plane::Plane_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::stereo_plane::Plane_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::stereo_plane::Plane_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::stereo_plane::Plane_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.point);
    stream.next(m.normal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Plane_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stereo_plane::Plane_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::stereo_plane::Plane_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "point: ";
s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
    s << indent << "normal: ";
s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.normal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // STEREO_PLANE_MESSAGE_PLANE_H

