/* Auto-generated by genmsg_cpp for file /home/mckoval/ros-diamondback/navi_stack/wiimote/msg/LEDControl.msg */
#ifndef WIIMOTE_MESSAGE_LEDCONTROL_H
#define WIIMOTE_MESSAGE_LEDCONTROL_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "wiimote/TimedSwitch.h"

namespace wiimote
{
template <class ContainerAllocator>
struct LEDControl_ : public ros::Message
{
  typedef LEDControl_<ContainerAllocator> Type;

  LEDControl_()
  : timed_switch_array()
  {
  }

  LEDControl_(const ContainerAllocator& _alloc)
  : timed_switch_array(_alloc)
  {
  }

  typedef std::vector< ::wiimote::TimedSwitch_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::wiimote::TimedSwitch_<ContainerAllocator> >::other >  _timed_switch_array_type;
  std::vector< ::wiimote::TimedSwitch_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::wiimote::TimedSwitch_<ContainerAllocator> >::other >  timed_switch_array;


  ROS_DEPRECATED uint32_t get_timed_switch_array_size() const { return (uint32_t)timed_switch_array.size(); }
  ROS_DEPRECATED void set_timed_switch_array_size(uint32_t size) { timed_switch_array.resize((size_t)size); }
  ROS_DEPRECATED void get_timed_switch_array_vec(std::vector< ::wiimote::TimedSwitch_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::wiimote::TimedSwitch_<ContainerAllocator> >::other > & vec) const { vec = this->timed_switch_array; }
  ROS_DEPRECATED void set_timed_switch_array_vec(const std::vector< ::wiimote::TimedSwitch_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::wiimote::TimedSwitch_<ContainerAllocator> >::other > & vec) { this->timed_switch_array = vec; }
private:
  static const char* __s_getDataType_() { return "wiimote/LEDControl"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "d0477eee2c164b8a9582a596f92c6f08"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# Message to request Wiimote LED operations. The Wiimote has four\n\
# LEDs. This message enables its user to turn each individual LED\n\
# on or off, and to define a blink pattern for each LEDs.\n\
#        See TimedSwitch.msg for details.\n\
\n\
TimedSwitch[] timed_switch_array  \n\
\n\
================================================================================\n\
MSG: wiimote/TimedSwitch\n\
# TimedSwitch allows sender to:\n\
#    o turn a switch on,\n\
#    o turn a switch off, and\n\
#    o repeat an on/off pattern forever or for a\n\
#          given number of times.\n\
# Fields (refer to definitions of constants in the definition body):\n\
#     o switch_mode:\n\
#         ON: turn on  (num_cycles and pulse_pattern fields are ignored)\n\
#        OFF: turn off (num_cycles and pulse_pattern fields are ignored)\n\
#  NO_CHANGE: leave LED in its current state\n\
#     REPEAT: repeat an on/off pattern for as long\n\
#             as is indicated in the num_cycles field. The\n\
#             pattern is defined in the pulse_pattern field.\n\
#\n\
#     o num_cycles:\n\
#          n>=0: run the pattern that is defined in pulse_pattern\n\
#                n times.\n\
#          n==FOREVER: run the pattern that is defined in pulse_pattern\n\
#                       until a new TimedSwitch message is sent.              \n\
#\n\
#     o pulse_pattern:\n\
#          A series of time durations in fractions of a second. The\n\
#          first number is the duration for having the switch on.\n\
#          The second number is the duration for which the switch\n\
#          is off. The third is an 'on' period again, etc.\n\
#          A pattern is terminated with the end of the array.\n\
#           \n\
#          Example: [1,1] specifies an on-off sequence of 1 second.               \n\
\n\
int8 ON        =  1\n\
int8 OFF       =  0\n\
int8 NO_CHANGE = -2\n\
int8 REPEAT    = -1\n\
int8 FOREVER   = -1\n\
\n\
int8 switch_mode\n\
int32 num_cycles\n\
float32[] pulse_pattern\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, timed_switch_array);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, timed_switch_array);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(timed_switch_array);
    return size;
  }

  typedef boost::shared_ptr< ::wiimote::LEDControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wiimote::LEDControl_<ContainerAllocator>  const> ConstPtr;
}; // struct LEDControl
typedef  ::wiimote::LEDControl_<std::allocator<void> > LEDControl;

typedef boost::shared_ptr< ::wiimote::LEDControl> LEDControlPtr;
typedef boost::shared_ptr< ::wiimote::LEDControl const> LEDControlConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::wiimote::LEDControl_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::wiimote::LEDControl_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace wiimote

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::wiimote::LEDControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d0477eee2c164b8a9582a596f92c6f08";
  }

  static const char* value(const  ::wiimote::LEDControl_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd0477eee2c164b8aULL;
  static const uint64_t static_value2 = 0x9582a596f92c6f08ULL;
};

template<class ContainerAllocator>
struct DataType< ::wiimote::LEDControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wiimote/LEDControl";
  }

  static const char* value(const  ::wiimote::LEDControl_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wiimote::LEDControl_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# Message to request Wiimote LED operations. The Wiimote has four\n\
# LEDs. This message enables its user to turn each individual LED\n\
# on or off, and to define a blink pattern for each LEDs.\n\
#        See TimedSwitch.msg for details.\n\
\n\
TimedSwitch[] timed_switch_array  \n\
\n\
================================================================================\n\
MSG: wiimote/TimedSwitch\n\
# TimedSwitch allows sender to:\n\
#    o turn a switch on,\n\
#    o turn a switch off, and\n\
#    o repeat an on/off pattern forever or for a\n\
#          given number of times.\n\
# Fields (refer to definitions of constants in the definition body):\n\
#     o switch_mode:\n\
#         ON: turn on  (num_cycles and pulse_pattern fields are ignored)\n\
#        OFF: turn off (num_cycles and pulse_pattern fields are ignored)\n\
#  NO_CHANGE: leave LED in its current state\n\
#     REPEAT: repeat an on/off pattern for as long\n\
#             as is indicated in the num_cycles field. The\n\
#             pattern is defined in the pulse_pattern field.\n\
#\n\
#     o num_cycles:\n\
#          n>=0: run the pattern that is defined in pulse_pattern\n\
#                n times.\n\
#          n==FOREVER: run the pattern that is defined in pulse_pattern\n\
#                       until a new TimedSwitch message is sent.              \n\
#\n\
#     o pulse_pattern:\n\
#          A series of time durations in fractions of a second. The\n\
#          first number is the duration for having the switch on.\n\
#          The second number is the duration for which the switch\n\
#          is off. The third is an 'on' period again, etc.\n\
#          A pattern is terminated with the end of the array.\n\
#           \n\
#          Example: [1,1] specifies an on-off sequence of 1 second.               \n\
\n\
int8 ON        =  1\n\
int8 OFF       =  0\n\
int8 NO_CHANGE = -2\n\
int8 REPEAT    = -1\n\
int8 FOREVER   = -1\n\
\n\
int8 switch_mode\n\
int32 num_cycles\n\
float32[] pulse_pattern\n\
\n\
";
  }

  static const char* value(const  ::wiimote::LEDControl_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wiimote::LEDControl_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.timed_switch_array);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LEDControl_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wiimote::LEDControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::wiimote::LEDControl_<ContainerAllocator> & v) 
  {
    s << indent << "timed_switch_array[]" << std::endl;
    for (size_t i = 0; i < v.timed_switch_array.size(); ++i)
    {
      s << indent << "  timed_switch_array[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::wiimote::TimedSwitch_<ContainerAllocator> >::stream(s, indent + "    ", v.timed_switch_array[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // WIIMOTE_MESSAGE_LEDCONTROL_H

